name: CI

on: [push]

env:
  CROSS_VERSION: 0.2.5

jobs:
  cross_build:
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        rust_versoin:
         - 1.67.1
         - 1.68.0
         - 1.76.0
        target:
         - i686-linux-android # ERROR
         - x86_64-linux-android # ERROR
         - x86_64-unknown-linux-musl # WORKS
    runs-on: ubuntu-22.04
    steps:
      - run: rustup default ${{ matrix.rust_versoin }}
      - uses: actions/checkout@v4
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross#f272b470f999c7e588fbcf5c0a159d14b5485ff4
      - run: cross build --target=${{ matrix.target }} --release --locked
        working-directory: ./cross-android-cannot-find-lunwind

