name: node18-http-server-stops-request

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       node-version: [14.21.3, 16.20.0, 17.9.1, 18.0.0, 18.15.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt install -y pv
    - run: |
        sudo tcpdump -i any -n "host 127.0.0.1 and port 3000" -w node-${{ matrix.node-version }}.pcap &
        echo $! > tcpdump.pid
    - name: Start server1
      run: |
        node node18-http-server-stops-request/server1.js > server1.log &
        sleep 2
    - name: Request
      run: seq 100 | pv -L 10 | curl -sST- http://127.0.0.1:3000
    - name: Show server1 log
      if: ${{ always() }}
      run: cat server1.log
    - name: Stop tcpdump
      if: ${{ always() }}
      run: |
        sleep 10
        sudo kill -INT $(cat tcpdump.pid)
        sleep 10
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: node-${{ matrix.node-version }}.pcap
        path: node-${{ matrix.node-version }}.pcap
